name: "Roam Research backup"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Run email2roam
        run: |
          cd ..
          git clone -q https://github.com/arn4v/email2roam.git email2roam
          cd $_
          npm i
          npm run start
        env:
          E2R_MODE: ${{ secrets.E2R_MODE }}
          ROAM_EMAIL: ${{ secrets.ROAM_EMAIL }}
          ROAM_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
          ROAM_GRAPH: ${{ secrets.ROAM_GRAPH }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          ALLOWED: ${{ secrets.ALLOWED }}
